#!/usr/bin/env python3
"""
hadamard_step2.py — v1's two problems fixed.

FIX 1 (bug): sp.symmetrize was handed a Poly; it wants an expression. That
path is dropped entirely — the reduction below (substitute r2 = e1 - r1, then
reduce modulo r1^2 - e1 r1 + e2) is exact, self-contained, and needs no
sympy symmetric-function helper.

FIX 2 (cost): v1 spent 142s expanding F1, F2 as series to v^16. Unnecessary —
factor_recs.py already VERIFIED the recurrences, so A and B are generated by
recursion after a short series start:
    A: X_k + d1 X_{k-1} + d2 X_{k-2} = 0                for k >= 3
    B: X_k + 2d1 X_{k-1} + (d1^2+2d2) X_{k-2}
         + 2 d1 d2 X_{k-3} + d2^2 X_{k-4} = 0           for k >= 5
(B's operator is A's squared — denominator D^2 — as it must be.)
Series is needed only up to v^4.

THE CONSTRUCTION (no ansatz, no search). A is C-finite with characteristic
roots r1, r2 of Y^2 + d1 Y + d2 = 0; B has the same roots each doubled. The
Hadamard product C_m = A_m B_m is C-finite with characteristic roots the
pairwise products {r1^2, r1 r2, r2^2}, multiplicities inherited, so it is
annihilated by the operator with characteristic polynomial
    (Y - r1^2)^2 (Y - r1 r2)^2 (Y - r2^2)^2      -- DEGREE 6.
Its coefficients are symmetric in r1, r2, hence lie in Q(t,z,w) via
    e1 = r1 + r2 = -d1,   e2 = r1 r2 = d2.
[Note: degree 6 is the same order the data-driven hunt measured for eX.]

VERIFICATION: the operator is applied to the ACTUAL C_m and each residual is
simplified to zero as a rational function of (t,z,w) — exact, not sampled.

Run:  python3 hadamard_step2.py     (plain python3; sympy only)
Writes hadamard_step2_results.json — SEND THIS BACK. Prints progress and
writes partial results as it goes.
"""
import sympy as sp, json, time

v, t, z, w, Y, r1 = sp.symbols('v t z w Y r1')

d1 = sp.expand(1 + t - z*t - w)
d2 = sp.expand(t*(1 - z - w))
D = 1 + d1*v + d2*v**2
F1 = (1 + v)*(1 + v*t)/D
F2 = -t*v**2*(1 + v)*(1 + v*t)/D**2

results = {"d1": sp.sstr(d1), "d2": sp.sstr(d2)}
T0 = time.time()

# ---------------------------------------------------------------- A, B
print("short series start (to v^4) ...", flush=True)
def coeffs(expr, upto):
    ser = sp.expand(sp.series(expr, v, 0, upto+1).removeO())
    return [sp.cancel(sp.together(ser.coeff(v, k))) for k in range(upto+1)]
A = coeffs(F1, 4)
B = coeffs(F2, 4)
print("   done (%.0fs)" % (time.time()-T0), flush=True)

NMAX = 14
cA = [sp.Integer(1), d1, d2]                                  # X_k + d1 X_{k-1} + d2 X_{k-2}
cB = [sp.Integer(1), sp.expand(2*d1), sp.expand(d1**2 + 2*d2),
      sp.expand(2*d1*d2), sp.expand(d2**2)]
for k in range(5, NMAX+1):
    if len(A) <= k:
        A.append(sp.cancel(sp.together(-(cA[1]*A[k-1] + cA[2]*A[k-2]))))
    if len(B) <= k:
        B.append(sp.cancel(sp.together(
            -(cB[1]*B[k-1] + cB[2]*B[k-2] + cB[3]*B[k-3] + cB[4]*B[k-4]))))
while len(A) <= NMAX:
    k = len(A)
    A.append(sp.cancel(sp.together(-(cA[1]*A[k-1] + cA[2]*A[k-2]))))
while len(B) <= NMAX:
    k = len(B)
    B.append(sp.cancel(sp.together(
        -(cB[1]*B[k-1] + cB[2]*B[k-2] + cB[3]*B[k-3] + cB[4]*B[k-4]))))

C = [sp.cancel(sp.together(A[k]*B[k])) for k in range(NMAX+1)]
results["C_first"] = [sp.sstr(sp.factor(c)) for c in C[:5]]
print("A,B,C generated to index %d (%.0fs)" % (NMAX, time.time()-T0), flush=True)

# ------------------------------------------------- characteristic polynomial
e1 = sp.expand(-d1)     # r1 + r2
e2 = sp.expand(d2)      # r1 * r2
r2sub = e1 - r1
minpoly = sp.Poly(r1**2 - e1*r1 + e2, r1)

charY = sp.expand((Y - r1**2)**2 * (Y - r1*r2sub)**2 * (Y - r2sub**2)**2)
cpoly = sp.Poly(charY, Y)
print("\nreducing degree-%d characteristic polynomial to Q(t,z,w) ..."
      % cpoly.degree(), flush=True)
red = []
for k, c in zip(range(cpoly.degree(), -1, -1), cpoly.all_coeffs()):
    rem = sp.rem(sp.Poly(sp.expand(c), r1), minpoly)
    expr = sp.expand(rem.as_expr())
    if r1 in expr.free_symbols:
        # symmetric functions must reduce to constants in r1; if not, report
        expr = sp.simplify(expr)
    red.append(sp.cancel(sp.together(expr)))
    left = r1 in red[-1].free_symbols
    print("   Y^%d done%s (%.0fs)" % (k, "  [WARNING: r1 survives]" if left else "",
                                      time.time()-T0), flush=True)
results["char_degree"] = cpoly.degree()
results["char_coeffs_Y_desc"] = [sp.sstr(sp.factor(c)) for c in red]
results["r1_survives_anywhere"] = any(r1 in c.free_symbols for c in red)
json.dump(results, open("hadamard_step2_results.json", "w"), indent=1)

# ------------------------------------------------- verify on actual C_m
print("\nverifying on actual C_m ...", flush=True)
order = len(red) - 1
bad, tested = [], 0
for k in range(order, NMAX+1):
    tot = sum(red[j]*C[k-j] for j in range(order+1))
    ok = (sp.simplify(sp.cancel(sp.together(tot))) == 0)
    if not ok: bad.append(k)
    tested += 1
    print("   k=%d: %s (%.0fs)" % (k, "ok" if ok else "FAIL", time.time()-T0),
          flush=True)
    results["verified_up_to"] = k
    results["failures"] = bad[:8]
    json.dump(results, open("hadamard_step2_results.json", "w"), indent=1)

results["operator_annihilates_C"] = (not bad)
results["indices_tested"] = tested
print("\nOPERATOR ANNIHILATES C_m = A_m*B_m:", not bad)
if bad:
    print("   failures at", bad[:8], "— if these are only the lowest indices,")
    print("   the operator is right and the inhomogeneous head runs further.")

results["next"] = ("e_X(m) = <k!j!>[t^m](2 A_m B_m). C_m is now annihilated by "
                   "an explicit degree-6 constant-coefficient (in m) operator "
                   "over Q(t,z,w). Remaining: the [t^m] DIAGONAL (m is both "
                   "index and t-exponent), then (d_z-1),(d_w-1) with the "
                   "z=0 / w=0 numerator-vanishing boundary kills.")
json.dump(results, open("hadamard_step2_results.json", "w"), indent=1)
print("wrote hadamard_step2_results.json — send this back")
