# wpart_gate.sage — gate ore_algebra on an answer we already proved.
#
#   sage wpart_gate.sage
#
# WHY THIS FIRST. The Hertzsprung control validated ct() for one differential
# direction with an e^{-z} factor. The a_{2,2} target needs more: a SHIFT in m
# alongside umbral directions. Before encoding that, exercise the mixed
# shift+differential machinery on something whose answer is proved.
#
# THE TARGET (proved exactly over Q, certificate verified symbolically):
#     e_W(m) = <m!>[ z^2 (z-1)^{2m-2} ]  =  2, 14, 362, 18806, ...
#     order 2:  p0 = -m(2m-1)(2m+3),
#               p1 = (8m^3+32m^2+32m+7)/2,
#               p2 = -(2m+1)/2
# and the odd analogue
#     o_W(m) = <m!>[ z^2 (z-1)^{2m-3} ]  =  4, 64, 2428, 165016, ...
#     order 2:  -2(m-1)(m+1)(2m-1),  4m^3+10m^2+3m-1,  -m
#
# THE ENCODING. With the umbral functional realised as integration against
# e^{-z}, the integrand is
#     F(z; m) = z^2 (z-1)^{2m-2} e^{-z}          (even case)
# Annihilators, in the algebra generated by Sm (shift in m) and Dz:
#     Sm  acts as multiplication by (z-1)^2      ->  ann_m = Sm - (z-1)^2
#     d/dz log F = 2/z + (2m-2)/(z-1) - 1
#       -> ann_z = z(z-1) Dz - [ 2(z-1) + (2m-2) z - z(z-1) ]
# The e^{-z} contributes the "-1", i.e. the "- z(z-1)" term after clearing --
# the same sign that was wrong for two days in the Hertzsprung encoding, so it
# is written out explicitly here and the script tries BOTH signs.
#
# ct(Dz) should then return an operator in Sm alone. A run is trusted only if
# that operator matches the proved one up to a rational scalar in m.

import json
from ore_algebra import *

R.<m, z> = ZZ[]
A.<Sm, Dz> = OreAlgebra(R)
print("algebra:", A)
print()

out = {}

def target_even():
    # p0 + p1 Sm + p2 Sm^2, cleared of the halves
    p0 = -2*m*(2*m-1)*(2*m+3)
    p1 = 8*m^3 + 32*m^2 + 32*m + 7
    p2 = -(2*m+1)
    return [p0, p1, p2]

def target_odd():
    return [-2*(m-1)*(m+1)*(2*m-1), 4*m^3 + 10*m^2 + 3*m - 1, -m]

def try_case(tag, shift_mult, dlog_num, dlog_den, targ):
    """shift_mult: multiplier for Sm.  dlog_num/dlog_den: d/dz log of the
    z-dependent part WITHOUT the e^{-z}; the exponential is added separately
    in both sign conventions."""
    res = {}
    for sgn_tag, sgn in (("MINUS (e^{-z}, derived)", -1), ("PLUS (wrong sign)", +1)):
        print("=" * 60)
        print("%s   %s" % (tag, sgn_tag))
        ann_m = Sm - shift_mult
        ann_z = dlog_den*Dz - (dlog_num + sgn*dlog_den)
        print("   ann_m =", ann_m)
        print("   ann_z =", ann_z)
        try:
            I = A.ideal([ann_m, ann_z])
            T, C = I.ct(Dz)
            gens = list(T)
            print("   telescoper:", gens)
            print("   certificate:", list(C))
            rec = {"ann_m": str(ann_m), "ann_z": str(ann_z),
                   "telescoper": [str(g) for g in gens],
                   "certificates": [str(c) for c in C]}
            matched = False
            for g in gens:
                cf = g.coefficients(sparse=False)
                if len(cf) != len(targ):
                    continue
                # compare up to an overall rational function in m
                ok = True
                ratio = None
                for a_, b_ in zip([R(c) for c in cf], targ):
                    if b_ == 0:
                        if a_ != 0: ok = False; break
                        continue
                    if ratio is None:
                        ratio = (a_, b_)
                    else:
                        if expand(a_*ratio[1] - b_*ratio[0]) != 0:
                            ok = False; break
                if ok:
                    matched = True
                    print("   >>> MATCHES the proved operator")
            rec["matches_proved"] = matched
            if not matched:
                print("   does NOT match the proved operator")
            res[sgn_tag] = rec
        except Exception as e:
            print("   ERROR:", str(e)[:300])
            res[sgn_tag] = {"error": str(e)[:400]}
        print()
    return res

# ---- even: F = z^2 (z-1)^{2m-2} e^{-z}
#      d/dz log[z^2 (z-1)^{2m-2}] = 2/z + (2m-2)/(z-1)
#      common denominator z(z-1):  num = 2(z-1) + (2m-2) z
out["even"] = try_case("EVEN  e_W",
                       (z-1)^2,
                       2*(z-1) + (2*m-2)*z,
                       z*(z-1),
                       target_even())

# ---- odd: F = z^2 (z-1)^{2m-3} e^{-z}
out["odd"] = try_case("ODD   o_W",
                      (z-1)^2,
                      2*(z-1) + (2*m-3)*z,
                      z*(z-1),
                      target_odd())

with open("wpart_gate_results.json", "w") as f:
    json.dump(out, f, indent=1)
print("wrote wpart_gate_results.json — send this back")
